<?php

/**
 * Implements hook_install().
 */
function ntl_install() {
  // Create the categories vocabulary.
  $description = st('High level categories to create some basic sortings');
  $help = st('Enter a comma-separated list of words to describe your content.');
  $vocabulary = (object) array(
    'name' => st('Site-Category'),
    'description' => $description,
    'machine_name' => 'site_category',
    'help' => $help,

  );
  taxonomy_vocabulary_save($vocabulary);
}
